services:
  <service name>:
    image: <which image>
    restart: <policy>
    environment:
      KEY: ${VALUE_FROM_ENV_FILE}
      ...
    volumes:
      - <volume name>:/var/lib/postgresql/data

volumes:
  <volume name>: